-- ENUM for roles
do $$ begin
  create type public.user_role as enum ('user','cafe_owner','superadmin');
exception when duplicate_object then null; end $$;

-- profiles table (1:1 with auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'user',
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cafes (
  id bigint generated by default as identity primary key,
  name text not null,
  neighborhood text,
  lat double precision,
  lng double precision,
  rating numeric(2,1),
  tags text[] default '{}',
  price text check (price in ('$', '$$', '$$$')),
  image_url text,
  owner_id uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  cafe_id bigint not null references public.cafes(id) on delete cascade,
  title text not null,
  start_at timestamptz,
  price numeric(10,2),
  tags text[] default '{}',
  created_at timestamptz not null default now()
);

-- RLS
alter table public.profiles enable row level security;
alter table public.cafes enable row level security;
alter table public.plans enable row level security;

-- Profiles policies
drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read" on public.profiles
for select using (auth.uid() = id or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'superadmin'));

drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_update" on public.profiles
for update using (auth.uid() = id or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'superadmin'));

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self" on public.profiles
for insert with check (auth.uid() = id);

-- Cafes policies
drop policy if exists "cafes_public_read" on public.cafes;
create policy "cafes_public_read" on public.cafes
for select using (true);

drop policy if exists "cafes_owner_write" on public.cafes;
create policy "cafes_owner_write" on public.cafes
for all using (
  owner_id = auth.uid()
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'superadmin')
) with check (
  owner_id = auth.uid()
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'superadmin')
);

-- Plans policies
drop policy if exists "plans_public_read" on public.plans;
create policy "plans_public_read" on public.plans
for select using (true);

drop policy if exists "plans_owner_write" on public.plans;
create policy "plans_owner_write" on public.plans
for all using (
  exists (
    select 1 from public.cafes c
    where c.id = cafe_id
      and (c.owner_id = auth.uid()
           or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'superadmin'))
  )
) with check (
  exists (
    select 1 from public.cafes c
    where c.id = cafe_id
      and (c.owner_id = auth.uid()
           or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'superadmin'))
  )
);

-- Ensure a profile row exists on sign-up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Indexes for common filters
create index if not exists cafes_neighborhood_idx on public.cafes (neighborhood);
create index if not exists cafes_price_idx on public.cafes (price);
create index if not exists cafes_tags_gin on public.cafes using gin (tags);
create index if not exists plans_cafe_id_idx on public.plans (cafe_id);

comment on table public.cafes is 'Cafés list for Bogotá Coffee Explorer';
comment on table public.plans is 'Plans/events related to cafes';
comment on table public.profiles is 'User profiles with roles user, cafe_owner, superadmin';
